name: tailscale-rdesktop-warpbuild

on:
  workflow_dispatch:

jobs:
  rdesktop-test:
    name: Tailscale SSH Rdesktop - WarpBuild
    uses: ./.github/workflows/reusable-tailscale-rdesktop.yml
    with:
      runs-on: "warp-ubuntu-latest-x64-2x"
      image: "ghcr.io/gbraad-gaming/cardforge:latest"
      hostname: "gaming-cardforge"
    secrets: inherit
