name: tailscale-rdesktop

on:
  workflow_dispatch:

jobs:
  rdesktop-test:
    name: Tailscale SSH Machine - GitHub
    uses: ./.github/workflows/reusable-tailscale-rdesktop.yml
    with:
      runs-on: "ubuntu-latest"
      image: "ghcr.io/gbraad-gaming/cardforge:latest"
      hostname: "gaming-cardforge"
    secrets: inherit
